// Code generated by generate.sh, DO NOT EDIT.

package nasMessage

import (
	"bytes"
	"encoding/binary"
	"fmt"

	"github.com/mimetrix/nas/nasType"
)

type RegistrationReject struct {
	nasType.ExtendedProtocolDiscriminator       `json:"ExtendedProtocolDiscriminator,omitempty"`
	nasType.SpareHalfOctetAndSecurityHeaderType `json:"SpareHalfOctetAndSecurityHeaderType,omitempty"`
	nasType.RegistrationRejectMessageIdentity   `json:"RegistrationRejectMessageIdentity,omitempty"`
	nasType.Cause5GMM                           `json:"Cause5GMM,omitempty"`
	*nasType.T3346Value                         `json:"T3346Value,omitempty"`
	*nasType.T3502Value                         `json:"T3502Value,omitempty"`
	*nasType.EAPMessage                         `json:"EAPMessage,omitempty"`
}

func NewRegistrationReject(iei uint8) (registrationReject *RegistrationReject) {
	registrationReject = &RegistrationReject{}
	return registrationReject
}

const (
	RegistrationRejectT3346ValueType uint8 = 0x5F
	RegistrationRejectT3502ValueType uint8 = 0x16
	RegistrationRejectEAPMessageType uint8 = 0x78
)

func (a *RegistrationReject) EncodeRegistrationReject(buffer *bytes.Buffer) error {
	if err := binary.Write(buffer, binary.BigEndian, a.ExtendedProtocolDiscriminator.Octet); err != nil {
		return fmt.Errorf("NAS encode error (RegistrationReject/ExtendedProtocolDiscriminator): %w", err)
	}
	if err := binary.Write(buffer, binary.BigEndian, a.SpareHalfOctetAndSecurityHeaderType.Octet); err != nil {
		return fmt.Errorf("NAS encode error (RegistrationReject/SpareHalfOctetAndSecurityHeaderType): %w", err)
	}
	if err := binary.Write(buffer, binary.BigEndian, a.RegistrationRejectMessageIdentity.Octet); err != nil {
		return fmt.Errorf("NAS encode error (RegistrationReject/RegistrationRejectMessageIdentity): %w", err)
	}
	if err := binary.Write(buffer, binary.BigEndian, a.Cause5GMM.Octet); err != nil {
		return fmt.Errorf("NAS encode error (RegistrationReject/Cause5GMM): %w", err)
	}
	if a.T3346Value != nil {
		if err := binary.Write(buffer, binary.BigEndian, a.T3346Value.GetIei()); err != nil {
			return fmt.Errorf("NAS encode error (RegistrationReject/T3346Value): %w", err)
		}
		if err := binary.Write(buffer, binary.BigEndian, a.T3346Value.GetLen()); err != nil {
			return fmt.Errorf("NAS encode error (RegistrationReject/T3346Value): %w", err)
		}
		if err := binary.Write(buffer, binary.BigEndian, a.T3346Value.Octet); err != nil {
			return fmt.Errorf("NAS encode error (RegistrationReject/T3346Value): %w", err)
		}
	}
	if a.T3502Value != nil {
		if err := binary.Write(buffer, binary.BigEndian, a.T3502Value.GetIei()); err != nil {
			return fmt.Errorf("NAS encode error (RegistrationReject/T3502Value): %w", err)
		}
		if err := binary.Write(buffer, binary.BigEndian, a.T3502Value.GetLen()); err != nil {
			return fmt.Errorf("NAS encode error (RegistrationReject/T3502Value): %w", err)
		}
		if err := binary.Write(buffer, binary.BigEndian, a.T3502Value.Octet); err != nil {
			return fmt.Errorf("NAS encode error (RegistrationReject/T3502Value): %w", err)
		}
	}
	if a.EAPMessage != nil {
		if err := binary.Write(buffer, binary.BigEndian, a.EAPMessage.GetIei()); err != nil {
			return fmt.Errorf("NAS encode error (RegistrationReject/EAPMessage): %w", err)
		}
		if err := binary.Write(buffer, binary.BigEndian, a.EAPMessage.GetLen()); err != nil {
			return fmt.Errorf("NAS encode error (RegistrationReject/EAPMessage): %w", err)
		}
		if err := binary.Write(buffer, binary.BigEndian, a.EAPMessage.Buffer); err != nil {
			return fmt.Errorf("NAS encode error (RegistrationReject/EAPMessage): %w", err)
		}
	}
	return nil
}

func (a *RegistrationReject) DecodeRegistrationReject(byteArray *[]byte) error {
	buffer := bytes.NewBuffer(*byteArray)
	if err := binary.Read(buffer, binary.BigEndian, &a.ExtendedProtocolDiscriminator.Octet); err != nil {
		return fmt.Errorf("NAS decode error (RegistrationReject/ExtendedProtocolDiscriminator): %w", err)
	}
	_ = a.ExtendedProtocolDiscriminator.DecodeNASType()
	if err := binary.Read(buffer, binary.BigEndian, &a.SpareHalfOctetAndSecurityHeaderType.Octet); err != nil {
		return fmt.Errorf("NAS decode error (RegistrationReject/SpareHalfOctetAndSecurityHeaderType): %w", err)
	}
	_ = a.SpareHalfOctetAndSecurityHeaderType.DecodeNASType()
	if err := binary.Read(buffer, binary.BigEndian, &a.RegistrationRejectMessageIdentity.Octet); err != nil {
		return fmt.Errorf("NAS decode error (RegistrationReject/RegistrationRejectMessageIdentity): %w", err)
	}
	if err := binary.Read(buffer, binary.BigEndian, &a.Cause5GMM.Octet); err != nil {
		return fmt.Errorf("NAS decode error (RegistrationReject/Cause5GMM): %w", err)
	}
	_ = a.Cause5GMM.DecodeNASType()
	for buffer.Len() > 0 {
		var ieiN uint8
		var tmpIeiN uint8
		if err := binary.Read(buffer, binary.BigEndian, &ieiN); err != nil {
			return fmt.Errorf("NAS decode error (RegistrationReject/iei): %w", err)
		}
		// fmt.Println(ieiN)
		if ieiN >= 0x80 {
			tmpIeiN = (ieiN & 0xf0) >> 4
		} else {
			tmpIeiN = ieiN
		}
		// fmt.Println("type", tmpIeiN)
		switch tmpIeiN {
		case RegistrationRejectT3346ValueType:
			a.T3346Value = nasType.NewT3346Value(ieiN)
			if err := binary.Read(buffer, binary.BigEndian, &a.T3346Value.Len); err != nil {
				return fmt.Errorf("NAS decode error (RegistrationReject/T3346Value): %w", err)
			}
			if a.T3346Value.Len != 1 {
				// Non-conformant length: skip this IE rather than
				// discarding the rest of the message.
				a.T3346Value = nil
				break
			}
			a.T3346Value.SetLen(a.T3346Value.GetLen())
			if err := binary.Read(buffer, binary.BigEndian, &a.T3346Value.Octet); err != nil {
				return fmt.Errorf("NAS decode error (RegistrationReject/T3346Value): %w", err)
			}
		case RegistrationRejectT3502ValueType:
			a.T3502Value = nasType.NewT3502Value(ieiN)
			if err := binary.Read(buffer, binary.BigEndian, &a.T3502Value.Len); err != nil {
				return fmt.Errorf("NAS decode error (RegistrationReject/T3502Value): %w", err)
			}
			if a.T3502Value.Len != 1 {
				// Non-conformant length: skip this IE rather than
				// discarding the rest of the message.
				a.T3502Value = nil
				break
			}
			a.T3502Value.SetLen(a.T3502Value.GetLen())
			if err := binary.Read(buffer, binary.BigEndian, &a.T3502Value.Octet); err != nil {
				return fmt.Errorf("NAS decode error (RegistrationReject/T3502Value): %w", err)
			}
		case RegistrationRejectEAPMessageType:
			a.EAPMessage = nasType.NewEAPMessage(ieiN)
			if err := binary.Read(buffer, binary.BigEndian, &a.EAPMessage.Len); err != nil {
				return fmt.Errorf("NAS decode error (RegistrationReject/EAPMessage): %w", err)
			}
			if a.EAPMessage.Len < 4 || a.EAPMessage.Len > 1500 {
				// Non-conformant length: skip this IE rather than
				// discarding the rest of the message.
				a.EAPMessage = nil
				break
			}
			a.EAPMessage.SetLen(a.EAPMessage.GetLen())
			if err := binary.Read(buffer, binary.BigEndian, a.EAPMessage.Buffer); err != nil {
				return fmt.Errorf("NAS decode error (RegistrationReject/EAPMessage): %w", err)
			}
			_ = a.EAPMessage.DecodeNASType()
		default:
		}
	}
	return nil
}
