// Code generated by generate.sh, DO NOT EDIT.

package nasMessage

import (
	"bytes"
	"encoding/binary"
	"fmt"

	"github.com/mimetrix/nas/nasType"
)

type PDUSessionAuthenticationComplete struct {
	nasType.ExtendedProtocolDiscriminator                   `json:"ExtendedProtocolDiscriminator,omitempty"`
	nasType.PDUSessionID                                    `json:"PDUSessionID,omitempty"`
	nasType.PTI                                             `json:"PTI,omitempty"`
	nasType.PDUSESSIONAUTHENTICATIONCOMPLETEMessageIdentity `json:"PDUSESSIONAUTHENTICATIONCOMPLETEMessageIdentity,omitempty"`
	nasType.EAPMessage                                      `json:"EAPMessage,omitempty"`
	*nasType.ExtendedProtocolConfigurationOptions           `json:"ExtendedProtocolConfigurationOptions,omitempty"`
}

func NewPDUSessionAuthenticationComplete(iei uint8) (pDUSessionAuthenticationComplete *PDUSessionAuthenticationComplete) {
	pDUSessionAuthenticationComplete = &PDUSessionAuthenticationComplete{}
	return pDUSessionAuthenticationComplete
}

const (
	PDUSessionAuthenticationCompleteExtendedProtocolConfigurationOptionsType uint8 = 0x7B
)

func (a *PDUSessionAuthenticationComplete) EncodePDUSessionAuthenticationComplete(buffer *bytes.Buffer) error {
	if err := binary.Write(buffer, binary.BigEndian, a.ExtendedProtocolDiscriminator.Octet); err != nil {
		return fmt.Errorf("NAS encode error (PDUSessionAuthenticationComplete/ExtendedProtocolDiscriminator): %w", err)
	}
	if err := binary.Write(buffer, binary.BigEndian, a.PDUSessionID.Octet); err != nil {
		return fmt.Errorf("NAS encode error (PDUSessionAuthenticationComplete/PDUSessionID): %w", err)
	}
	if err := binary.Write(buffer, binary.BigEndian, a.PTI.Octet); err != nil {
		return fmt.Errorf("NAS encode error (PDUSessionAuthenticationComplete/PTI): %w", err)
	}
	if err := binary.Write(buffer, binary.BigEndian, a.PDUSESSIONAUTHENTICATIONCOMPLETEMessageIdentity.Octet); err != nil {
		return fmt.Errorf("NAS encode error (PDUSessionAuthenticationComplete/PDUSESSIONAUTHENTICATIONCOMPLETEMessageIdentity): %w", err)
	}
	if err := binary.Write(buffer, binary.BigEndian, a.EAPMessage.GetLen()); err != nil {
		return fmt.Errorf("NAS encode error (PDUSessionAuthenticationComplete/EAPMessage): %w", err)
	}
	if err := binary.Write(buffer, binary.BigEndian, a.EAPMessage.Buffer); err != nil {
		return fmt.Errorf("NAS encode error (PDUSessionAuthenticationComplete/EAPMessage): %w", err)
	}
	if a.ExtendedProtocolConfigurationOptions != nil {
		if err := binary.Write(buffer, binary.BigEndian, a.ExtendedProtocolConfigurationOptions.GetIei()); err != nil {
			return fmt.Errorf("NAS encode error (PDUSessionAuthenticationComplete/ExtendedProtocolConfigurationOptions): %w", err)
		}
		if err := binary.Write(buffer, binary.BigEndian, a.ExtendedProtocolConfigurationOptions.GetLen()); err != nil {
			return fmt.Errorf("NAS encode error (PDUSessionAuthenticationComplete/ExtendedProtocolConfigurationOptions): %w", err)
		}
		if err := binary.Write(buffer, binary.BigEndian, a.ExtendedProtocolConfigurationOptions.Buffer); err != nil {
			return fmt.Errorf("NAS encode error (PDUSessionAuthenticationComplete/ExtendedProtocolConfigurationOptions): %w", err)
		}
	}
	return nil
}

func (a *PDUSessionAuthenticationComplete) DecodePDUSessionAuthenticationComplete(byteArray *[]byte) error {
	buffer := bytes.NewBuffer(*byteArray)
	if err := binary.Read(buffer, binary.BigEndian, &a.ExtendedProtocolDiscriminator.Octet); err != nil {
		return fmt.Errorf("NAS decode error (PDUSessionAuthenticationComplete/ExtendedProtocolDiscriminator): %w", err)
	}
	_ = a.ExtendedProtocolDiscriminator.DecodeNASType()
	if err := binary.Read(buffer, binary.BigEndian, &a.PDUSessionID.Octet); err != nil {
		return fmt.Errorf("NAS decode error (PDUSessionAuthenticationComplete/PDUSessionID): %w", err)
	}
	if err := binary.Read(buffer, binary.BigEndian, &a.PTI.Octet); err != nil {
		return fmt.Errorf("NAS decode error (PDUSessionAuthenticationComplete/PTI): %w", err)
	}
	if err := binary.Read(buffer, binary.BigEndian, &a.PDUSESSIONAUTHENTICATIONCOMPLETEMessageIdentity.Octet); err != nil {
		return fmt.Errorf("NAS decode error (PDUSessionAuthenticationComplete/PDUSESSIONAUTHENTICATIONCOMPLETEMessageIdentity): %w", err)
	}
	if err := binary.Read(buffer, binary.BigEndian, &a.EAPMessage.Len); err != nil {
		return fmt.Errorf("NAS decode error (PDUSessionAuthenticationComplete/EAPMessage): %w", err)
	}
	if a.EAPMessage.Len < 4 || a.EAPMessage.Len > 1500 {
		return fmt.Errorf("invalid ie length (PDUSessionAuthenticationComplete/EAPMessage): %d", a.EAPMessage.Len)
	}
	a.EAPMessage.SetLen(a.EAPMessage.GetLen())
	if err := binary.Read(buffer, binary.BigEndian, a.EAPMessage.Buffer); err != nil {
		return fmt.Errorf("NAS decode error (PDUSessionAuthenticationComplete/EAPMessage): %w", err)
	}
	_ = a.EAPMessage.DecodeNASType()
	for buffer.Len() > 0 {
		var ieiN uint8
		var tmpIeiN uint8
		if err := binary.Read(buffer, binary.BigEndian, &ieiN); err != nil {
			return fmt.Errorf("NAS decode error (PDUSessionAuthenticationComplete/iei): %w", err)
		}
		// fmt.Println(ieiN)
		if ieiN >= 0x80 {
			tmpIeiN = (ieiN & 0xf0) >> 4
		} else {
			tmpIeiN = ieiN
		}
		// fmt.Println("type", tmpIeiN)
		switch tmpIeiN {
		case PDUSessionAuthenticationCompleteExtendedProtocolConfigurationOptionsType:
			a.ExtendedProtocolConfigurationOptions = nasType.NewExtendedProtocolConfigurationOptions(ieiN)
			if err := binary.Read(buffer, binary.BigEndian, &a.ExtendedProtocolConfigurationOptions.Len); err != nil {
				return fmt.Errorf("NAS decode error (PDUSessionAuthenticationComplete/ExtendedProtocolConfigurationOptions): %w", err)
			}
			if a.ExtendedProtocolConfigurationOptions.Len < 1 {
				// Non-conformant length: skip this IE rather than
				// discarding the rest of the message.
				a.ExtendedProtocolConfigurationOptions = nil
				break
			}
			a.ExtendedProtocolConfigurationOptions.SetLen(a.ExtendedProtocolConfigurationOptions.GetLen())
			if err := binary.Read(buffer, binary.BigEndian, a.ExtendedProtocolConfigurationOptions.Buffer); err != nil {
				return fmt.Errorf("NAS decode error (PDUSessionAuthenticationComplete/ExtendedProtocolConfigurationOptions): %w", err)
			}
			_ = a.ExtendedProtocolConfigurationOptions.DecodeNASType()
		default:
		}
	}
	return nil
}
