// Code generated by generate.sh, DO NOT EDIT.

package nasMessage

import (
	"bytes"
	"encoding/binary"
	"fmt"

	"github.com/mimetrix/nas/nasType"
)

type SecurityProtected5GSNASMessage struct {
	nasType.ExtendedProtocolDiscriminator       `json:"ExtendedProtocolDiscriminator,omitempty"`
	nasType.SpareHalfOctetAndSecurityHeaderType `json:"SpareHalfOctetAndSecurityHeaderType,omitempty"`
	nasType.MessageAuthenticationCode           `json:"MessageAuthenticationCode,omitempty"`
	nasType.SequenceNumber                      `json:"SequenceNumber"`

	// FORK: upstream models the protected payload as an opaque
	// nasType.Plain5GSNASMessage blob. For observability we recursively
	// decode it into a full Message instead, which is what exposes the
	// inner message to consumers.
	PlainNASMessage *Message
}

func NewSecurityProtected5GSNASMessage(iei uint8) (securityProtected5GSNASMessage *SecurityProtected5GSNASMessage) {
	securityProtected5GSNASMessage = &SecurityProtected5GSNASMessage{}
	return securityProtected5GSNASMessage
}

func (a *SecurityProtected5GSNASMessage) EncodeSecurityProtected5GSNASMessage(buffer *bytes.Buffer) error {
	if err := binary.Write(buffer, binary.BigEndian, a.ExtendedProtocolDiscriminator.Octet); err != nil {
		return fmt.Errorf("NAS encode error (SecurityProtected5GSNASMessage/ExtendedProtocolDiscriminator): %w", err)
	}
	if err := binary.Write(buffer, binary.BigEndian, a.SpareHalfOctetAndSecurityHeaderType.Octet); err != nil {
		return fmt.Errorf("NAS encode error (SecurityProtected5GSNASMessage/SpareHalfOctetAndSecurityHeaderType): %w", err)
	}
	if err := binary.Write(buffer, binary.BigEndian, a.MessageAuthenticationCode.Octet[:]); err != nil {
		return fmt.Errorf("NAS encode error (SecurityProtected5GSNASMessage/MessageAuthenticationCode): %w", err)
	}
	if err := binary.Write(buffer, binary.BigEndian, a.SequenceNumber.Octet); err != nil {
		return fmt.Errorf("NAS encode error (SecurityProtected5GSNASMessage/SequenceNumber): %w", err)
	}
	if a.PlainNASMessage != nil {
		b, err := a.PlainNASMessage.PlainNasEncode()
		if err != nil {
			return fmt.Errorf("NAS encode error (SecurityProtected5GSNASMessage/PlainNASMessage): %w", err)
		}
		if err := binary.Write(buffer, binary.BigEndian, b); err != nil {
			return fmt.Errorf("NAS encode error (SecurityProtected5GSNASMessage/PlainNASMessage): %w", err)
		}
	}
	return nil
}

func (a *SecurityProtected5GSNASMessage) DecodeSecurityProtected5GSNASMessage(byteArray *[]byte) error {
	buffer := bytes.NewBuffer(*byteArray)
	if err := binary.Read(buffer, binary.BigEndian, &a.ExtendedProtocolDiscriminator.Octet); err != nil {
		return fmt.Errorf("NAS decode error (SecurityProtected5GSNASMessage/ExtendedProtocolDiscriminator): %w", err)
	}
	if err := a.ExtendedProtocolDiscriminator.DecodeNASType(); err != nil {
		return fmt.Errorf("NAS decode error (SecurityProtected5GSNASMessage/ExtendedProtocolDiscriminator): %w", err)
	}
	if err := binary.Read(buffer, binary.BigEndian, &a.SpareHalfOctetAndSecurityHeaderType.Octet); err != nil {
		return fmt.Errorf("NAS decode error (SecurityProtected5GSNASMessage/SpareHalfOctetAndSecurityHeaderType): %w", err)
	}
	if err := a.SpareHalfOctetAndSecurityHeaderType.DecodeNASType(); err != nil {
		return fmt.Errorf("NAS decode error (SecurityProtected5GSNASMessage/SpareHalfOctetAndSecurityHeaderType): %w", err)
	}
	if err := binary.Read(buffer, binary.BigEndian, a.MessageAuthenticationCode.Octet[:]); err != nil {
		return fmt.Errorf("NAS decode error (SecurityProtected5GSNASMessage/MessageAuthenticationCode): %w", err)
	}
	if err := a.MessageAuthenticationCode.DecodeNASType(); err != nil {
		return fmt.Errorf("NAS decode error (SecurityProtected5GSNASMessage/MessageAuthenticationCode): %w", err)
	}
	if err := binary.Read(buffer, binary.BigEndian, &a.SequenceNumber.Octet); err != nil {
		return fmt.Errorf("NAS decode error (SecurityProtected5GSNASMessage/SequenceNumber): %w", err)
	}
	// FORK: recursively decode the protected payload rather than reading it
	// as an opaque blob. A failure here is not fatal: the outer header is
	// still useful (and the payload may simply be ciphertext we cannot
	// decrypt), so record what we can and continue.
	if b := buffer.Bytes(); len(b) > 0 {
		inner := &Message{}
		if err := inner.PlainNasDecode(&b); err == nil {
			a.PlainNASMessage = inner
		}
	}
	for buffer.Len() > 0 {
		var ieiN uint8
		var tmpIeiN uint8
		if err := binary.Read(buffer, binary.BigEndian, &ieiN); err != nil {
			return fmt.Errorf("NAS decode error (SecurityProtected5GSNASMessage/iei): %w", err)
		}
		// fmt.Println(ieiN)
		if ieiN >= 0x80 {
			tmpIeiN = (ieiN & 0xf0) >> 4
		} else {
			tmpIeiN = ieiN
		}
		// fmt.Println("type", tmpIeiN)
		switch tmpIeiN {
		default:
		}
	}
	return nil
}
